language: r

sudo: required

env:
  global:
    - WARNINGS_ARE_ERRORS=1
  matrix:
    - NOT_CRAN="true"
    - NOT_CRAN="false"

r_binary_packages:
  - knitr

r_github_packages:
  - jimhester/covr
after_success:
  - Rscript -e 'covr::coveralls()'