##' @title Print a summary of an \code{\linkS4class{meta.data}} object
##' @param x a \code{\linkS4class{meta.data}} object generated by \code{\link{document}}
##' @param ... optional additional parameters. 
##' @return Values to the screen.
##' @note Not complete
##' @method print meta.data
##' @export
print.meta.data <- function(x, ...){
  cat("Showing metadata for object: ")
  cat(unlist(x@description), "\n")
  cat("Data from following sources: \n", unique(unlist(x@sources)), "\n")
  cat("Data expressed in: \n", unlist(x@units),"\n")
  cat("Additional notes: \n", unlist(x@annotations), "\n")
  cat("Revision history: \n", unlist(x@revisions), "\n")
  }

#' @title Summarize a meta.data
#' @description This is a function to summarize a meta.data
#' @param object An object of class meta.data
#' @param ... ignored
##' @method summary meta.data
#' @export
summary.meta.data <- function(object, ...){
  # message("Not written yet.")
}


#' @title Display the structure of a meta.data object
#' @description This is a function to display the internal structure of a meta.data
#' @param object An object of class meta.data
#' @param ... ignored
#' @export
str.meta.data <- function(object, ...){
  # message("Not written yet.")
}
